export const ERROR_CODES: { [key: string]: string } = {
  'auth/email-already-in-use':
    'The email address is already in use by another account.',
  'auth/invalid-email': 'The email address is not valid.',
  'auth/user-not-found':
    'There is no user corresponding to the given email address.',
  'auth/wrong-password': 'The password is incorrect.',
  'auth/weak-password':
    'The password is too weak. Please choose a stronger password.',
  'auth/user-disabled': 'The user account has been disabled.',
  'auth/operation-not-allowed': 'The requested operation is not allowed.',
  'auth/credential-already-in-use':
    'The credential is already associated with another user account.',
  'auth/invalid-verification-code': 'The verification code is invalid.',
  'auth/missing-verification-code':
    'A verification code is required for phone authentication, but it was not provided.',
  'auth/admin-restricted-operation':
    'This operation is restricted to administrators only.',
  'auth/argument-error': 'Error during authentication',
  'auth/app-not-authorized':
    'The app is not authorized to use Firebase Authentication. Please check your Firebase project configuration.',
  'auth/app-not-installed': '',
  'auth/captcha-check-failed': '',
  'auth/code-expired': '',
  'auth/cordova-not-ready': '',
  'auth/cors-unsupported': '',
  'auth/custom-token-mismatch': '',
  'auth/requires-recent-login': '',
  'auth/dependent-sdk-initialized-before-auth': '',
  'auth/dynamic-link-not-activated': '',
  'auth/email-change-needs-verification': '',
  'auth/emulator-config-failed': '',
  'auth/expired-action-code': '',
  'auth/cancelled-popup-request': '',
  'auth/internal-error': '',
  'auth/invalid-api-key': '',
  'auth/invalid-app-credential': '',
  'auth/invalid-app-id': '',
  'auth/invalid-user-token': '',
  'auth/invalid-auth-event': '',
  'auth/invalid-cert-hash': '',
  'auth/invalid-continue-uri': '',
  'auth/invalid-cordova-configuration': '',
  'auth/invalid-custom-token': '',
  'auth/invalid-dynamic-link-domain': '',
  'auth/invalid-emulator-scheme': '',
  'auth/invalid-credential': '',
  'auth/invalid-message-payload': '',
  'auth/invalid-multi-factor-session': '',
  'auth/invalid-oauth-client-id': '',
  'auth/invalid-oauth-provider': '',
  'auth/invalid-action-code': '',
  'auth/unauthorized-domain': '',
  'auth/invalid-persistence-type': '',
  'auth/invalid-phone-number': '',
  'auth/invalid-provider-id': '',
  'auth/invalid-recipient-email': '',
  'auth/invalid-sender': '',
  'auth/invalid-verification-id': '',
  'auth/invalid-tenant-id': '',
  'auth/multi-factor-info-not-found': '',
  'auth/multi-factor-auth-required': '',
  'auth/missing-android-pkg-name': '',
  'auth/missing-app-credential': '',
  'auth/auth-domain-config-required': '',
  'auth/missing-continue-uri': '',
  'auth/missing-iframe-start': '',
  'auth/missing-ios-bundle-id': '',
  'auth/missing-or-invalid-nonce': '',
  'auth/missing-multi-factor-info': '',
  'auth/missing-multi-factor-session': '',
  'auth/missing-phone-number': '',
  'auth/missing-verification-id': '',
  'auth/app-deleted': '',
  'auth/account-exists-with-different-credential': '',
  'auth/network-request-failed': '',
  'auth/null-user': '',
  'auth/no-auth-event': '',
  'auth/no-such-provider': '',
  'auth/operation-not-supported-in-this-environment': '',
  'auth/popup-blocked': '',
  'auth/popup-closed-by-user': '',
  'auth/provider-already-linked': '',
  'auth/quota-exceeded': '',
  'auth/redirect-cancelled-by-user': '',
  'auth/redirect-operation-pending': '',
  'auth/rejected-credential': '',
  'auth/second-factor-already-in-use': '',
  'auth/maximum-second-factor-count-exceeded': '',
  'auth/tenant-id-mismatch': '',
  'auth/timeout': '',
  'auth/user-token-expired': '',
  'auth/too-many-requests': '',
  'auth/unauthorized-continue-uri': '',
  'auth/unsupported-first-factor': '',
  'auth/unsupported-persistence-type': '',
  'auth/unsupported-tenant-operation': '',
  'auth/unverified-email': '',
  'auth/user-cancelled': '',
  'auth/user-mismatch': '',
  'auth/user-signed-out': '',
  'auth/web-storage-unsupported': '',
  'auth/already-initialized': '',
  'auth/recaptcha-not-enabled': '',
  'auth/missing-recaptcha-token': '',
  'auth/invalid-recaptcha-token': '',
  'auth/invalid-recaptcha-action': '',
  'auth/missing-client-type': '',
  'auth/missing-recaptcha-version': '',
  'auth/invalid-recaptcha-version': '',
  'auth/invalid-req-type': '',
};
